name: erp_mobile
description: Aplicativo ERP integrado com Supabase
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  sign_in_with_apple: ^7.0.1
  intl: ^0.18.0
  mobile_scanner: ^3.2.0
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3

flutter:
  uses-material-design: true